web/views.py
from flask import Blueprint, render_template, url_for, request, redirect

from back.models import Article,ArticleType

web_blue = Blueprint('web',__name__)



@web_blue.route('/home/',methods = ['GET'])
def home():
        articles = Article.query.all()
        return render_template('/web/home.html',articles = articles)


@web_blue.route('/article/',methods = ['GET','POST'])
def article():
    types = ArticleType.query.all()
    articles = Article.query.all()
    return render_template('/web/article.html',articles = articles, types = types)


@web_blue.route('/resource/',methods = ['GET'])
def resource():
    return render_template('/web/resource.html')


@web_blue.route('/timeline/',methods = ['GET'])
def timeline():
    return render_template('/web/timeline.html')


@web_blue.route('/about/',methods = ['GET'])
def about():
    return render_template('/web/about.html')


@web_blue.route('/detail/<int:id>/',methods = ['GET'])
def detail(id):
    types = ArticleType.query.all()
    article = Article.query.get(id)
    return render_template('/web/detail.html',article = article,types=types)

@web_blue.route('/article_type/<int:id_t>/',methods = ['GET'])
def article_type(id_t):
    types = ArticleType.query.all()
    type = ArticleType.query.get(id_t)
    articles = type.arts
    return render_template('/web/article.html',articles = articles, types = types)


@web_blue.route('/search/',methods = ['GET','POST'])
def search():
    if request.method == 'POST':
        keywords = request.form.get('keywords')
        if keywords:
            types = ArticleType.query.filter(ArticleType.t_name.contains('%s' % keywords)).all()
            if not types:
                error = '没有相关类型，请重新输入！！！'
                return render_template('/web/article.html',error=error)
            return render_template('/web/article.html',types=types)
        else:
            error = '请输入完整信息！！！'
            return render_template('/web/article.html', error=error)

templates/web/article.html
{% extends '/web/base_main.html' %}

{% block title %}
    烽火-文章专栏
{% endblock %}

{% block css %}
    {{super()}}
    <!--本页样式表-->
    <link href="/static/web/css/article.css" rel="stylesheet" />
{% endblock %}

{% block content %}
    {{super()}}
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <div class="blog-container">
            <blockquote class="layui-elem-quote sitemap layui-breadcrumb shadow">
                <a href="home.html" title="网站首页">网站首页</a>
                <a><cite>文章专栏</cite></a>
            </blockquote>
            <div class="blog-main">
                <div class="blog-main-left">
                    {% for article in articles %}
                        <div class="article shadow">
                            <div class="article-left">
                                <img src="/static/web/images/cover/201703181909057125.jpg" alt="基于laypage的layui扩展模块（pagesize.js）！" />
                            </div>
                            <div class="article-right">
                                <div class="article-title">
                                    <a href="{{ url_for('web.detail',id = article.id) }}">{{ article.title }}</a>
                                </div>
                                <div class="article-abstract">
                                    {{ article.content }}
                                </div>
                            </div>
                            <div class="clear"></div>
                            <div class="article-footer">
                                <span><i class="fa fa-clock-o"></i>&nbsp;&nbsp;{{ article.create_time }}</span>
                                <span><i class="fa fa-tag"></i>&nbsp;&nbsp;<a href="#">{{ article.tp.t_name }}</a></span>
                                <span class="article-viewinfo"><i class="fa fa-eye"></i>&nbsp;0</span>
                                <span class="article-viewinfo"><i class="fa fa-commenting"></i>&nbsp;4</span>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="blog-main-right">
                    <div class="blog-search">
                        <form class="layui-form" action="/web/search/" method="post">
                            <div class="layui-form-item">
                                <div class="search-keywords  shadow">
                                    <p style="color: red;">{{error}}</p>
                                    <input type="text" name="keywords" lay-verify="required" placeholder="输入关键词搜索" autocomplete="off" class="layui-input">
                                </div>
                                <div class="search-submit  shadow">
                                    <button class="search-btn" type="submit"><i class="fa fa-search"></i></button>
                                    <!--<input type="submit" class="search-btn" value="">-->
                                    <!--<a class="search-btn" lay-submit="formSearch" lay-filter="formSearch"><i class="fa fa-search"></i></a>-->
                                </div>
                            </div>
                        </form>

                    </div>
                    <div class="article-category shadow">
                        <div class="article-category-title">分类导航</div>
                        {% for type in types %}
                        <a href="{{ url_for('web.article_type',id_t=type.id) }}">{{type.t_name}}</a>
                        {% endfor %}
                        <div class="clear"></div>
                    </div>
                    <!--右边悬浮 平板或手机设备显示-->
                    <div class="category-toggle"><i class="fa fa-chevron-left"></i></div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!-- 底部 -->
    <footer class="blog-footer">
        <p><span>zack</span><span>&copy;</span><span></span><a href="{{ url_for('web.home') }}">烽火</a><span>Design By zack</span></p>
    </footer>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>
{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/web/base_main.html
{% extends '/web/base.html' %}

{% block css %}
    <link rel="shortcut icon" href="/static/web/images/Logo_40.png" type="image/x-icon">
    <link href="/static/web/plug/layui/css/layui.css" rel="stylesheet" />
    <link href="/static/web/plug/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/static/web/css/global.css" rel="stylesheet" />
{% endblock %}

{% block content %}
    <!-- 导航 -->
    <nav class="blog-nav layui-header">
        <div class="blog-container">
            <!-- QQ互联登陆 -->
            <a href="javascript:;" class="blog-user">
                <i class="fa fa-qq"></i>
            </a>
            <a href="javascript:;" class="blog-user layui-hide">
                <img src="/static/web/images/cover/qq.png" alt="Absolutely" title="烽火" />
            </a>
            <!-- 烽火 -->
            <a class="blog-logo" href="/web/home/">烽火</a>
            <!-- 导航菜单 -->
            <ul class="layui-nav" lay-filter="nav">
                <li class="layui-nav-item layui-this">
                    <a href="{{ url_for('web.home') }}"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{{ url_for('web.article') }}"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{{ url_for('web.resource') }}"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{{ url_for('web.timeline') }}"><i class="fa fa-hourglass-half fa-fw"></i>&nbsp;点点滴滴</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{{ url_for('web.about') }}"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
                </li>
            </ul>
            <!-- 手机和平板的导航开关 -->
            <a class="blog-navicon" href="javascript:;">
                <i class="fa fa-navicon"></i>
            </a>
        </div>
    </nav>
<!--侧边导航-->
    <ul class="layui-nav layui-nav-tree layui-nav-side blog-nav-left layui-hide" lay-filter="nav">
        <li class="layui-nav-item">
            <a href="{{ url_for('web.home') }}"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
        </li>
        <li class="layui-nav-item layui-this">
            <a href="{{ url_for('web.article') }}"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
        </li>
        <li class="layui-nav-item">
            <a href="{{ url_for('web.resource') }}"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
        </li>
        <li class="layui-nav-item">
            <a href="{{ url_for('web.timeline') }}"><i class="fa fa-road fa-fw"></i>&nbsp;点点滴滴</a>
        </li>
        <li class="layui-nav-item">
            <a href="{{ url_for('web.about') }}"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
        </li>
    </ul>
    <script src="/static/web/plug/layui/layui.js"></script>
    <script src="/static/web/js/global.js"></script>
{% endblock %}

templates/web/detail.html
{% extends '/web/base_main.html' %}

{% block title %}
    烽火 - 文章专栏
{% endblock %}

{% block css %}
    {{super()}}
    <!-- 比较好用的代码着色插件 -->
    <link href="/static/web/css/prettify.css" rel="stylesheet" />
    <!-- 本页样式表 -->
    <link href="/static/web/css/detail.css" rel="stylesheet" />
{% endblock %}

{% block content %}
    {{ super() }}
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <div class="blog-container">
            <blockquote class="layui-elem-quote sitemap layui-breadcrumb shadow">
                <a href="home.html" title="网站首页">网站首页</a>
                <a href="article.html" title="文章专栏">文章专栏</a>
                <a><cite>{{article.tp.t_name}}</cite></a>
            </blockquote>
            <div class="blog-main">
                <div class="blog-main-left">
                    <!-- 文章内容（使用Kingeditor富文本编辑器发表的） -->
                    <div class="article-detail shadow">
                        <div class="article-detail-title">
                            {{article.tp.t_name}}
                        </div>
                        <div class="article-detail-info">
                            <span>编辑时间：{{article.create_time}}</span>
                            <span>作者：{{article.owner.username}}</span>
                        </div>
                        <div class="article-detail-content">
                            <p style="text-align:center;">
                                <strong><span style="font-size:18px;">{{article.title}}</span></strong>
                            </p>
                            <p style="text-align:center;">
                                <strong>
                                    <span style="font-size:18px;">
                                        <br />
                                    </span>
                                </strong>
                            </p>
                            <p style="text-align:left;">
                                <br />
                            </p>
                            <p>
                                <br />
                            </p>
                            <hr />
                            <p>
                                <br />
                            </p>
                            <p>
                                {{ article.content }}
                            </p>
                            </p>
                            <hr />
                            &nbsp; &nbsp; 出自：{{article.owner.username}}

                            <p>
                                <br />
                            </p>
                        </div>
                    </div>
                    <!-- 评论区域 -->
                    <div class="blog-module shadow" style="box-shadow: 0 1px 8px #a6a6a6;">
                        <fieldset class="layui-elem-field layui-field-title" style="margin-bottom:0">
                            <legend>来说两句吧</legend>
                            <div class="layui-field-box">
                                <form class="layui-form blog-editor" action="">
                                    <div class="layui-form-item">
                                        <textarea name="editorContent" lay-verify="content" id="remarkEditor" placeholder="请输入内容" class="layui-textarea layui-hide"></textarea>
                                    </div>
                                    <div class="layui-form-item">
                                        <button class="layui-btn" lay-submit="formRemark" lay-filter="formRemark">提交评论</button>
                                    </div>
                                </form>
                            </div>
                        </fieldset>
                        <div class="blog-module-title">最新评论</div>
                        <ul class="blog-comment">
                            <li>
                                <div class="comment-parent">
                                    <img src="../images/Absolutely.jpg" alt="absolutely" />
                                    <div class="info">
                                        <span class="username">Absolutely</span>
                                        <span class="time">2017-03-18 18:46:06</span>
                                    </div>
                                    <div class="content">
                                        我为大家做了模拟评论功能！还有，这个评论功能也可以改成和留言一样，但是目前没改，有兴趣可以自己改
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="blog-main-right">
                    <!--右边悬浮 平板或手机设备显示-->
                    <div class="category-toggle"><i class="fa fa-chevron-left"></i></div><!--这个div位置不能改，否则需要添加一个div来代替它或者修改样式表-->
                    <div class="article-category shadow">
                        <div class="article-category-title">分类导航</div>
                        <!-- 点击分类后的页面和artile.html页面一样，只是数据是某一类别的 -->
                        {% for type in types %}
                        <a href="{{url_for('web.article_type',id_t = type.id)}}">{{type.t_name}}</a>
                        {% endfor %}
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <footer class="blog-footer">
        <p><span>zack</span><span>&copy;</span><span></span><a href="{{ url_for('web.home') }}">烽火</a><span>Design By zack</span></p>
    </footer>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>
    <!-- 比较好用的代码着色插件 -->
    <script src="/static/web/js/prettify.js"></script>
    <!-- 本页脚本 -->
    <script src="/static/web/js/detail.js"></script>
{% endblock %}

templates/web/home.html
{% extends '/web/base_main.html' %}

{% block title %}
    烽火 - 一个程序员的个人博客网站
{% endblock %}

{% block css %}
    {{ super() }}
    <!-- 本页样式表 -->
    <link href="/static/web/css/home.css" rel="stylesheet" />
{% endblock %}

{% block content %}
    {{ super() }}
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <!-- canvas -->
        <canvas id="canvas-banner" style="background: #393D49;"></canvas>
        <!--为了及时效果需要立即设置canvas宽高，否则就在home.js中设置-->
        <script type="text/javascript">
            var canvas = document.getElementById('canvas-banner');
            canvas.width = window.document.body.clientWidth - 10;//减去滚动条的宽度
            if (screen.width >= 992) {
                canvas.height = window.innerHeight * 1 / 3;
            } else {
                canvas.height = window.innerHeight * 2 / 7;
            }
        </script>
        <!-- 这个一般才是真正的主体内容 -->
        <div class="blog-container">
            <div class="blog-main">
                <!-- 网站公告提示 -->
                <div class="home-tips shadow">
                    <i style="float:left;line-height:17px;" class="fa fa-volume-up"></i>
                    <div class="home-tips-container">
                        <span style="color: #009688">欢迎来到郭锐的博客园</span>
                        <span style="color: red">网站还有留言回复功能哦！！</span>
                        <span style="color: #009688">烽火 &nbsp;—— &nbsp;一个.NET程序员的个人博客</span>
                    </div>
                </div>
                <!--左边文章列表-->
                <div class="blog-main-left">
                    {% for article in articles %}
                        <div class="article shadow">
                            <div class="article-left">
                                <img src="/static/web/images/cover/201703181909057125.jpg" alt="基于laypage的layui扩展模块（pagesize.js）！" />
                            </div>
                            <div class="article-right">
                                <div class="article-title">
                                    <a href="{{ url_for('web.detail',id = article.id) }}">{{ article.title }}</a>
                                </div>
                                <div class="article-abstract">
                                    {{ article.content }}
                                </div>
                            </div>
                            <div class="clear"></div>
                            <div class="article-footer">
                                <span><i class="fa fa-clock-o"></i>&nbsp;&nbsp;{{ article.create_time }}</span>
                                <span><i class="fa fa-tag"></i>&nbsp;&nbsp;<a href="#">{{ article.tp.t_name }}</a></span>
                                <span class="article-viewinfo"><i class="fa fa-eye"></i>&nbsp;0</span>
                                <span class="article-viewinfo"><i class="fa fa-commenting"></i>&nbsp;4</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!--右边小栏目-->
                <div class="blog-main-right">
                    <div class="blogerinfo shadow">
                        <div class="blogerinfo-figure">
                            <img src="/static/web/images/cover/qq.png" style="height: 40px;weight:40px" alt="烽火" />
                        </div>
                        <p class="blogerinfo-nickname">烽火</p>
                        <p class="blogerinfo-introduce">一枚90后python程序员，</p>
                        <p class="blogerinfo-location"><i class="fa fa-location-arrow"></i>&nbsp;四川 - 成都</p>
                        <hr />
                        <div class="blogerinfo-contact">
                            <a target="_blank" title="QQ交流" href="javascript:layer.msg('启动QQ会话窗口')"><i class="fa fa-qq fa-2x"></i></a>
                            <a target="_blank" title="给我写信" href="javascript:layer.msg('启动邮我窗口')"><i class="fa fa-envelope fa-2x"></i></a>
                            <a target="_blank" title="新浪微博" href="javascript:layer.msg('转到你的微博主页')"><i class="fa fa-weibo fa-2x"></i></a>
                            <a target="_blank" title="码云" href="javascript:layer.msg('转到你的github主页')"><i class="fa fa-git fa-2x"></i></a>
                        </div>
                    </div>
                    <div></div><!--占位-->
                    <div class="blog-module shadow">
                        <div class="blog-module-title">热文排行</div>
                        <ul class="fa-ul blog-module-ul">
                            {% for article in articles %}
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">{{ article.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">最近分享</div>
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="http://pan.baidu.com/s/1c1BJ6Qc" target="_blank">Canvas</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="http://pan.baidu.com/s/1kVK8UhT" target="_blank">pagesize.js</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="https://pan.baidu.com/s/1mit2aiW" target="_blank">时光轴</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="https://pan.baidu.com/s/1nuAKF81" target="_blank">图片轮播</a></li>
                        </ul>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">一路走来</div>
                        <dl class="footprint">
                            <dt>2017年03月12日</dt>
                            <dd>新增留言回复功能！人人都可参与回复！</dd>
                            <dt>2017年03月10日</dt>
                            <dd>不落阁2.0基本功能完成，正式上线！</dd>
                            <dt>2017年03月09日</dt>
                            <dd>新增文章搜索功能！</dd>
                            <dt>2017年02月25日</dt>
                            <dd>QQ互联接入网站，可QQ登陆发表评论与留言！</dd>
                        </dl>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">后台记录</div>
                        <dl class="footprint">
                            <dt>2017年03月16日</dt>
                            <dd>分页新增页容量控制</dd>
                            <dt>2017年03月12日</dt>
                            <dd>新增管家提醒功能</dd>
                            <dt>2017年03月10日</dt>
                            <dd>新增Win10快捷菜单</dd>
                        </dl>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">友情链接</div>
                        <ul class="blogroll">
                            <li><a target="_blank" href="https://www.python.org/" title="python官网">python下载地址</a></li>
                            <li><a target="_blank" href="https://www.jetbrains.com/pycharm/download/#section=windows" title="">pycharm专业版和社区版</a></li>
                        </ul>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <!-- 底部 -->
    <footer class="blog-footer">
        <p><span>zack</span><span>&copy;</span><span></span><a href="{{ url_for('web.home') }}">烽火</a><span>Design By zack</span></p>
    </footer>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>
    <!-- 本页脚本 -->
    <script src="/static/web/js/home.js"></script>
{% endblock %}

templates/web/resource.html
{% extends '/web/base_main.html' %}

{% block title %}
    烽火 - 资源分享
{% endblock %}

{% block css %}
    {{ super() }}
    <!-- 本页样式表 -->
    <link href="/static/web/css/resource.css" rel="stylesheet" />
{% endblock %}

{% block content %}
    {{ super() }}
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <div class="blog-container">
            <blockquote class="layui-elem-quote sitemap layui-breadcrumb shadow">
                <a href="home.html" title="网站首页">网站首页</a>
                <a><cite>资源分享</cite></a>
            </blockquote>
            <div class="blog-main">
                <div class="blog-main">
                    <div class="child-nav shadow">
                        <span class="child-nav-btn child-nav-btn-this">全部</span>
                        <span class="child-nav-btn">源码</span>
                        <span class="child-nav-btn">工具</span>
                        <span class="child-nav-btn">电子书</span>
                    </div>
                    <div class="resource-main">
                        <div class="resource shadow">
                            <div class="resource-cover">
                                <a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">
                                    <img src="../images/cover/201703051349045432.jpg" alt="时光轴" />
                                </a>
                            </div>
                            <h1 class="resource-title"><a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">时光轴</a></h1>
                            <p class="resource-abstract">本博客使用的时光轴的源码，手工打造！</p>
                            <div class="resource-info">
                                <span class="category"><a href="javascript:layer.msg(&#39;这里跳转到相应分类&#39;)"><i class="fa fa-tags fa-fw"></i>&nbsp;源码</a></span>
                                <span class="author"><i class="fa fa-user fa-fw"></i>Absolutely</span>
                                <div class="clear"></div>
                            </div>
                            <div class="resource-footer">
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank"><i class="fa fa-eye fa-fw"></i>演示</a>
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填下载地址&#39;)" target="_blank"><i class="fa fa-download fa-fw"></i>下载</a>
                            </div>
                        </div>
                        <!-- 清除浮动 -->
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <footer class="blog-footer">
        <p><span>zack</span><span>&copy;</span><span></span><a href="{{ url_for('web.home') }}">烽火</a><span>Design By zack</span></p>
    </footer>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>
{% endblock %}