back/models.py
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer,primary_key = True,autoincrement = True)
    username = db.Column(db.String(10),unique = True,nullable = False)
    password = db.Column(db.String(255),nullable = False)
    is_delete = db.Column(db.Boolean,default = 0)
    create_time = db.Column(db.DateTime,default = datetime.now())
    all_art = db.relationship('Article',backref = 'owner')

    __tablename__ = 'user'

    def save(self):
        db.session.add(self)
        db.session.commit()

class ArticleType(db.Model):
    id = db.Column(db.Integer,primary_key = True,autoincrement = True)
    t_name = db.Column(db.String(10),unique = True,nullable = False)
    arts = db.relationship('Article',backref = 'tp')
    __tablename__ = 'art_type'

class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(30), unique=True, nullable=False)
    desc = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text,nullable = False)
    create_time = db.Column(db.DateTime,default = datetime.now())
    type = db.Column(db.Integer,db.ForeignKey('art_type.id'))
    usertype = db.Column(db.Integer,db.ForeignKey('user.id'))

    __tablename__ = 'article'

back/__init__.py
"""zack"""


def main():
    pass


if __name__ == '__main__':
    main()

back/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.security import generate_password_hash,check_password_hash

from back.models import User, Article, ArticleType, db
from utils.functions import is_login

back_blue = Blueprint('back',__name__)



@back_blue.route('/index/')
@is_login
def index():
    return render_template('/back/index.html')

@back_blue.route('/register/',methods = ['GET','POST'])
def register():
    if request.method == 'GET':
        return render_template('/back/register.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if username and password and password2:
            user = User.query.filter(User.username == username).first()
            if user:
                error = '警告！该账号已经注册，请更换账号'
                return render_template('/back/register.html',error = error)
            if password != password2:
                error = '警告！两次输入密码不一致'
                return render_template('/back/register.html',error=error)
            user = User()
            user.username = username
            user.password = generate_password_hash(password)
            user.save()
            return redirect(url_for('back.login'))
        else:
            error = '警告！请填写完整的信息'
            return render_template('/back/register.html',error = error)

@back_blue.route('/login/',methods = ['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template('/back/login.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if username and password:
            user = User.query.filter(User.username == username).first()
            if not user:
                error = '警告！账号不存在，请去注册'
                return render_template('/back/login.html',error=error)
            if not check_password_hash(user.password,password):
                error = '警告！密码错误，请重新输入'
                return render_template('/back/login.html',error=error)
            session['user_id'] = user.id
            return redirect(url_for('back.index'))
        else:
            error = '警告！请填写完整的信息'
            return render_template('/back/login.html',error=error)

@back_blue.route('/logout/',methods = ['GET'])
def logout():
    del session['user_id']
    return redirect(url_for('back.login'))

@back_blue.route('/a_type/',methods = ['GET'])
def a_type():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/category_list.html',types = types)

@back_blue.route('/add_type/',methods = ['GET','POST'])
def add_type():
    if request.method == 'GET':
        return render_template('/back/category_add.html')
    if request.method == 'POST':
        atype = request.form.get('atype')
        if not atype:
            error = '警告！请填写分类信息'
            return render_template('/back/category_add.html',error=error)
        art_type = ArticleType()
        art_type.t_name = atype
        db.session.add(art_type)
        db.session.commit()
        return redirect(url_for('back.a_type'))

@back_blue.route('/del_type/<int:id>/',methods = ['GET'])
def del_type(id):
    atype = ArticleType.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.a_type'))

@back_blue.route('/article_list/',methods = ['GET'])
def article_list():
    usertype = session['user_id']
    articles = Article.query.filter(Article.usertype == usertype).all()
    return render_template('/back/article_list.html',articles = articles)

@back_blue.route('/article_detail/',methods = ['GET','POST'])
def article_add():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('/back/article_detail.html',types = types)
    if request.method == 'POST':
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        user_id = session['user_id']
        if title and desc and category and content:
            art = Article()
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            art.usertype = user_id
            print(art)
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article_list'))
        else:
            error = '请填写完整的文章信息'
            return render_template('/back/article_detail.html',error=error)

@back_blue.route('/user_list/',methods= ['GET'])
def user_list():
    users = User.query.all()
    return render_template('/back/user_list.html',users = users)

@back_blue.route('/del_user/<int:id>/',methods = ['GET'])
def del_user(id):
    user = User.query.get(id)
    user.is_delete = 1
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('back.user_list'))


@back_blue.route('/del_list/<int:id>/',methods = ['GET'])
def del_list(id):
    a_list = Article.query.get(id)
    db.session.delete(a_list)
    db.session.commit()
    return redirect(url_for('back.article_list'))


@back_blue.route('/edit/<int:id>',methods = ['GET','POST'])
def edit(id):
    if request.method == 'GET':
        types = ArticleType.query.all()
        a_edit = Article.query.get(id)
        return render_template('/back/edit.html',a_edit = a_edit,types = types)
    if request.method == 'POST':
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            art = Article.query.get(id)
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article_list'))
        else:
            error = '请填写完整的文章信息'
            return render_template('/back/edit.html', error=error)

web/views.py
from flask import Blueprint, render_template, url_for, request, redirect

from back.models import Article,ArticleType

web_blue = Blueprint('web',__name__)



@web_blue.route('/home/',methods = ['GET'])
def home():
        articles = Article.query.all()
        return render_template('/web/home.html',articles = articles)


@web_blue.route('/article/',methods = ['GET','POST'])
def article():
    types = ArticleType.query.all()
    articles = Article.query.all()
    return render_template('/web/article.html',articles = articles, types = types)


@web_blue.route('/resource/',methods = ['GET'])
def resource():
    return render_template('/web/resource.html')


@web_blue.route('/timeline/',methods = ['GET'])
def timeline():
    return render_template('/web/timeline.html')


@web_blue.route('/about/',methods = ['GET'])
def about():
    return render_template('/web/about.html')


@web_blue.route('/detail/<int:id>/',methods = ['GET'])
def detail(id):
    types = ArticleType.query.all()
    article = Article.query.get(id)
    return render_template('/web/detail.html',article = article,types=types)

@web_blue.route('/article_type/<int:id_t>/',methods = ['GET'])
def article_type(id_t):
    types = ArticleType.query.all()
    type = ArticleType.query.get(id_t)
    articles = type.arts
    return render_template('/web/article.html',articles = articles, types = types)


@web_blue.route('/search/',methods = ['GET','POST'])
def search():
    if request.method == 'POST':
        keywords = request.form.get('keywords')
        if keywords:
            types = ArticleType.query.filter(ArticleType.t_name.contains('%s' % keywords)).all()
            if not types:
                error = '没有相关类型，请重新输入！！！'
                return render_template('/web/article.html',error=error)
            return render_template('/web/article.html',types=types)
        else:
            error = '请输入完整信息！！！'
            return render_template('/web/article.html', error=error)

templates/back/article_detail.html
{% extends '/back/base_main.html' %}

{% block title %}
    文章添加
{% endblock %}

{% block js %}
    {{ super() }}

    
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id');
        });
    </script>
{% endblock %}


{% block content %}
    <section class="rt_wrap mCustomScrollbar">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">文章详情</h2>
                <a class="fr top_rt_btn" href="{{ url_for('back.article_list') }}">返回文章列表</a>
            </div>
            <form action="" method="post">
                {{ error }}
                <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
                <section>
                    <ul class="ulColumn2">
                        <li>
                            <span class="item_name" style="width:120px;">文章标题：</span>
                            <input type="text" name="name" value="" class="textbox textbox_295" placeholder="商品名称..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">文章描述：</span>
                            <input type="text" name="desc" value=""  class="textbox" placeholder="商品货号..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">分类：</span>
                            <select class="select" name="category">
                                    {% for type in types %}
                                    <option value="{{type.id}}">{{ type.t_name }}</option>
                                    {% endfor %}
                            </select>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">文章详情：</span>
                            <textarea id="editor_id" name="content" style="width:700px;height:300px;">
                        </textarea>
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
            <footer class="blog-footer">
        <p><span>zack</span><span>&copy;</span><span></span><a href="{{ url_for('web.home') }}">烽火</a><span>Design By zack</span></p>
    </footer>
    </section>
{% endblock %}

templates/back/article_list.html
{% extends '/back/base_main.html' %}

{% block title %}
    文章列表
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">文章列表</h2>
                <a href="{{ url_for('back.article_add') }}" class="fr top_rt_btn add_icon">添加文章</a>
            </div>
            <table class="table">
                <tr>
                    <th>文章标题</th>
                    <th>文章分类</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>
                {% for article in articles %}
                    <tr>
                        <td class="center">{{ article.title }}</td>
                        <td class="center">{{ article.type }}</td>
                        <td class="center">
                            {{ article.create_time }}
                        </td>
                        <td class="center">
                            <a href="{{ url_for('back.edit',id = article.id) }}" title="编辑" class="link_icon">&#101;</a>
                            <a href="{{ url_for('back.del_list',id=article.id) }}" onclick="" title="删除" class="link_icon">&#100;</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <aside class="paging">
                <a>当前1页</a>
                <a href="">第一页</a>

                    <a href=""> 1 </a>

                    <a href=""> 2 </a>

                    <a href=""> 3 </a>

                <a href="">最后一页</a>
            </aside>
        </div>
    </section>
{% endblock %}

templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block aside %}
{% endblock %}

{% block content %}
{% endblock %}
</body>
</html>

templates/back/base_main.html
{% extends '/back/base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
{% endblock %}

{% block js %}
    <script src="/static/back/js/jquery.js"></script>
    <script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock %}

{% block header %}
    <header>
        <h1><img src="/static/back/images/admin_logo.png"/></h1>
        <ul class="rt_nav">
            <li><a href="{{ url_for('back.index') }}" target="_blank" class="website_icon">站点首页</a></li>
            <li><a href="#" class="set_icon">账号设置</a></li>
            <li><a href="{{url_for('back.logout')}}" class="quit_icon">安全退出</a></li>
        </ul>
    </header>
{% endblock %}

{% block aside %}
    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">博客后台菜单栏</a></h2>
            <ul>
                <li>
                    <dl>
                        <dt>文章管理</dt>
                        <!--当前链接则添加class:active-->
                        <dd><a href="{{ url_for('back.a_type') }}">文章分类</a></dd>
                        <dd><a href="{{url_for('back.article_list')}}">文章列表</a></dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>用户管理</dt>
                        <dd><a href="{{ url_for('back.user_list') }}">用户信息</a></dd>
                    </dl>
                </li>
            </ul>
    </aside>
{% endblock %}

templates/back/category_add.html
{% extends '/back/base_main.html' %}

{% block title %}
    添加文章分类
{% endblock %}

{% block content %}
    <section class="rt_wrap mCustomScrollbar">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">文章分类</h2>
                <a class="fr top_rt_btn" href="goods_category_list.html">返回文章分类列表</a>
            </div>
            <form action="" method="post">
                {{ error }}
                <section>
                    <ul class="ulColumn2">
                        <li>
                            <span class="item_name" style="width:120px;">分类名称：</span>
                            <input type="text" name="atype">
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>
{% endblock %}

templates/back/category_list.html
{% extends '/back/base_main.html' %}



{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章列表</h2>
            <a href="{{url_for('back.add_type')}}" class="fr top_rt_btn add_icon">添加文章分类</a>
        </div>
        <table class="table">
            <tr>
                <th>类型</th>
                <th>操作</th>
            </tr>
            {% for type in types %}
                <tr>
                    <td class="center">
                        {{ type.t_name }}
                    </td>
                    <td class="center">
                        <a href="{{url_for('back.del_type',id=type.id)}}" title="删除" class="link_icon">&#101;</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock %}

templates/back/edit.html
{% extends '/back/base_main.html' %}

{% block title %}
    文章添加
{% endblock %}

{% block js %}
    {{ super() }}

    
    <script type="text/javascript" src="/static/lib/ueditor/ueditor.all.js"></script>
    <script type="text/javascript" src="/static/lib/lang/zh-cn/zh-cn.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id');
        });
    </script>
{% endblock %}


{% block content %}
    <section class="rt_wrap mCustomScrollbar">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">文章详情</h2>
                <a class="fr top_rt_btn" href="{{ url_for('back.article_list') }}">返回文章列表</a>
            </div>
            <form action="" method="post">
                <p style="color:red;">{{ error }}</p>
                <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
                <section>
                    <ul class="ulColumn2">
                        <li>
                            <span class="item_name" style="width:120px;">文章标题：</span>
                            <input type="text" name="name" value="{{ a_edit.title }}" class="textbox textbox_295" placeholder="商品名称..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">文章描述：</span>
                            <input type="text" name="desc" value="{{ a_edit.desc }}"  class="textbox" placeholder="商品货号..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">分类：</span>
                            <select class="select" name="category">
                                    {% for type in types %}
                                    <option value="{{type.id}}">{{ type.t_name }}</option>
                                    {% endfor %}
                            </select>

                        </li>
                        <li>
                            <span class="item_name" >文章详情：</span>
                            <textarea id="editor_id" name="content" style="width:700px;height:300px;">
                            {{ a_edit.content }}
                        </textarea>
                            <!--<textarea name="content"></textarea>-->
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>
{% endblock %}

templates/back/goods_desc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

    
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
         <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_list.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>



<section class="rt_wrap">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <input type='hidden' name='csrfmiddlewaretoken' value='QuPi2QUuEhlKchGijsQULGJKUZO6bOJacZPtDzGnIfWv89lLhtnbVM2EVRxtAXCJ' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">产品详情：</span>
                        <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                            <textarea id="editor_id" name="content" style="width:700px;"></textarea>
                        </label>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>



</body>
</html>

templates/back/index.html
{% extends '/back/base_main.html' %}

{% block title %}
博客后台管理系统
{% endblock %}

{% block js %}
{{ super() }}
<script src="/static/back/js/html5.js"></script>
<script>

(function($){
    $(window).load(function(){

        $("a[rel='load-content']").click(function(e){
            e.preventDefault();
            var url=$(this).attr("href");
            $.get(url,function(data){
                $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
                //scroll-to appended content
                $(".content").mCustomScrollbar("scrollTo","h2:last");
            });
        });

        $(".content").delegate("a[href='top']","click",function(e){
            e.preventDefault();
            $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
        });

    });
})(jQuery);
</script>
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
            博客城管理后台
        </h1>
        <br>
        <p>采用Flask开发，存储数据库为关系型数据库Mysql</p>
        <br>
        <p>后台集中功能为：文章发布、用户管理等</p>


    </div>
</section>
{% endblock %}

templates/back/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>后台登录</title>
<meta name="author" content="DeathGhost" />
<link rel="stylesheet" type="text/css" href="/static/back/css/style.css" />
<style>
body{height:100%;background:#16a085;overflow:hidden;}
canvas{z-index:-1;position:absolute;}
</style>
<script src="/static/back/js/jquery.js"></script>
<script src="/static/back/js/verificationNumbers.js"></script>
<script src="/static/back/js/Particleground.js"></script>
<script>
$(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
    dotColor: '#5cbdaa',
    lineColor: '#5cbdaa'
  });
  //验证码
  createCode();
  //测试提交，对接程序删除即可
  $(".submit_btn").click(function(){
	  location.href="index.html";
	  });
});
</script>
</head>
<body>
<dl class="admin_login">
 <dt>
  <strong>站点后台管理系统</strong>
  <em>Management System</em>
 </dt>
 <form action="" method="post">
     {{ error }}
    <dd class="user_icon">
         <input type="text" name="username" placeholder="账号" class="login_txtbx"/>
    </dd>
    <dd class="pwd_icon">
         <input type="password" name="password" placeholder="密码" class="login_txtbx"/>
    </dd>
    <dd>
         <input type="submit" value="立即登录" class="submit_btn"/>
    </dd>
 </form>
 <dd>
  <p>© 2015-2016 DeathGhost 版权所有</p>
  <p>陕B2-20080224-1</p>
 </dd>
</dl>
</body>
</html>

templates/back/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>

    <link rel="stylesheet" type="text/css" href="css/style.css">

    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_detail.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>




<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">订单列表</h2>
        </div>
        <table class="table">
            <tr>
                <th>订单编号</th>
                <th>收件人</th>
                <th>联系电话</th>
                <th>收件人地址</th>
                <th>订单金额</th>
                <th>配送方式</th>
                <!--<th>操作</th>-->
            </tr>
            
                <tr>
                    <td class="center">Pg5Wq4GYKWge6fhMDiMI</td>
                    <td>小花</td>
                    <td>12887754321</td>
                    <td>
                        <address>四川省成都市</address>
                    </td>
                    <td class="center"><strong class="rmb_icon">1260.0</strong></td>
                    <td class="center">申通快递</td>
                    <!--<td class="center">-->
                        <!--<a href="#" title="查看订单" class="link_icon" target="_blank">&#118;</a>-->
                    <!--</td>-->
                </tr>
        </table>
        <aside class="paging">
            <a>当前1页</a>
            <a href="">第一页</a>
            
                <a href=""> 1 </a>
                <a href=""> 2 </a>
                <a href=""> 3 </a>
                <a href=""> 4 </a>
            
            <a href="">最后一页</a>
        </aside>
    </div>
</section>



</body>
</html>

templates/back/user_list.html
{% extends '/back/base_main.html' %}

{% block title %}
    用户信息
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
     <div class="rt_content">
          <div class="page_title">
               <h2 class="fl">会员列表</h2>
               <a href="{{ url_for('back.register') }}" class="fr top_rt_btn add_icon">添加新会员</a>
          </div>
          <section class="mtb">
               <select class="select">
                    <option>会员等级</option>
                    <option>普通会员</option>
                    <option>高级会员</option>
               </select>
                   <input type="text" class="textbox textbox_225" placeholder="输入会员号/手机/电子邮件查询..."/>
                   <input type="button" value="查询" class="group_btn"/>
          </section>
          <table class="table">
           <tr>
            <th>Id</th>
            <th>会员账号</th>
            <th>会员创建时间</th>
            <th>操作</th>
           </tr>
              {% for user in users %}
                  {% if user.is_delete == 0 %}
                       <tr>
                            <td class="center">{{ user.id }}</td>
                            <td>{{ user.username }}</td>
                            <td class="center">{{ user.create_time }}</td>
                            <td class="center">
                                 <a href="user_detail.html" title="编辑" class="link_icon">&#101;</a>
                                 <a href="{{ url_for('back.del_user',id = user.id) }}" title="删除" class="link_icon">&#100;</a>
                            </td>
                       </tr>
                  {% endif %}
              {% endfor %}
          </table>
          <aside class="paging">
           <a>第一页</a>
           <a>1</a>
           <a>2</a>
           <a>3</a>
           <a>…</a>
           <a>1004</a>
           <a>最后一页</a>
          </aside>
     </div>
    </section>
{% endblock %}